#!/usr/bin/env python3
"""Refresh the brand logos (assets/brand-paths.ts) from the LATEST Simple Icons
release, so TikTok/Instagram/WhatsApp/... always look like today's apps.

    python3 S/scripts/update-brands.py            # writes S/assets/brand-paths.ts
    python3 S/scripts/update-brands.py --out src/talk/brand-paths.ts

Simple Icons is CC0. email/phone are generic Material Icons (Apache-2.0).
Colours live in assets/brands.tsx (BRANDS); check them against the real app
icons when a brand changes its look.
"""
import argparse
import json
import os
import re
import urllib.request

NAMES = ["tiktok", "facebook", "instagram", "whatsapp", "gmail", "youtube", "linkedin", "x", "telegram",
         "snapchat", "messenger", "googlemaps", "claude", "googlegemini", "openai"]
GENERIC = {
    "email": "M20 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z",
    "phone": "M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z",
}
BASE = "https://cdn.jsdelivr.net/npm/simple-icons@latest/"

ap = argparse.ArgumentParser()
ap.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "brand-paths.ts"))
a = ap.parse_args()


def get(url):
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read().decode("utf-8")


version = json.loads(get(BASE + "package.json"))["version"]
paths = {}
for n in NAMES:
    try:
        paths[n] = re.search(r' d="([^"]+)"', get(BASE + f"icons/{n}.svg")).group(1)
    except Exception as e:  # a brand left Simple Icons: keep going, say so
        print(f"  {n}: not available ({e})")
paths.update(GENERIC)
with open(a.out, "w", encoding="utf-8") as f:
    f.write(f"// GENERATED by scripts/update-brands.py from Simple Icons {version} (CC0) + Material Icons (Apache-2.0) for email/phone.\n")
    f.write("export const BRAND_PATHS: Record<string, string> = " + json.dumps(paths, indent=1) + ";\n")
print(f"{len(paths)} logos from Simple Icons {version} -> {a.out}")
